using Domen.AutoGenerated;
using Domen.EmtityDTO.Token;
using Domen.EmtityDTO.UserDto;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Aplication.Services.Token
{
    public class IdentityService : IIdentityServise
    {
        public Task<bool> IsValidRefreshToken(string refreshToken, int userId)
        {
            throw new NotImplementedException();
        }

        public Task<UserGetDto> LoginAsync(UserCreateDto userCreate)
        {
            throw new NotImplementedException();
        }

        public Task<bool> LogoutAsync()
        {
            throw new NotImplementedException();
        }

        public Task<TokenDto> RegisterAsync(User user)
        {
            throw new NotImplementedException();
        }
    }
}
