using Domen.AutoGenerated;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Aplication.Services.Token;

public interface IJwtTokenService
{
    string GenerateToken(User user);
}
