using Domen.AutoGenerated;
using System;
using System.Collections.Generic;
using System.Linq;
using Domen.Model;
using System.Threading.Tasks;
using Nest;

namespace Aplication.Services
{
    public  interface ITokenService
    {

        Task<AuthenticateResponse?> Authenticate(AuthenticateRequest model);
        Task<IEnumerable<User>> GetAll();
        Task<User?> GetById(int id);
        Task<User?> AddAndUpdateUser(User userObj);
    }
}
