using Domen.AutoGenerated;
using Infrastructure;
using Infrastructure.GenericRepository;
using Infrastructure.Repositories;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Domen.Repositories;

public class EmployeeRepository : GenericRepository<Employee>,IEmployeeRepository
{
    public EmployeeRepository(ConpanyDbContext conpanyDbContext) : base(conpanyDbContext)
    {
    }
}
