using Domen.AutoGenerated;
using Domen.EmtityDTO.Token;
using Domen.EmtityDTO.UserDto;
using Infrastructure.GenericRepository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Infrastructure.Repositories
{
    public  interface IUserRepository : IGenericRepository<User>
    {

        Task<UserGetDto> GetByUserNameAynce(string Name);
       Task<User>  GetUserByUsernameAndPasswordAsync(string username, string password);
    }
}
