using Domen.AutoGenerated;
using Infrastructure.GenericRepository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Infrastructure.Repositories
{
    public class OrganizationRepasitory : GenericRepository<Organization>, IOrganizationRepasitory
    {
        public OrganizationRepasitory(ConpanyDbContext conpanyDbContext) : base(conpanyDbContext)
        {
        }
    }
}
