using Infrastructure.GenericRepository;

using Task = Domen.AutoGenerated.Task;

namespace Infrastructure.Repositories
{
    public class TaskRepository : GenericRepository<Task>, ITaskRepository
    {
        public TaskRepository(ConpanyDbContext conpanyDbContext) : base(conpanyDbContext)
        {
        }
    }
}
