using Domen.AutoGenerated;
using Domen.EmtityDTO.UserDto;
using Infrastructure.GenericRepository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Infrastructure.Repositories
{
    public class UserRepository : GenericRepository<User>, IUserRepository
    {
        public UserRepository(ConpanyDbContext conpanyDbContext) : base(conpanyDbContext)
        {
        }

        public Task<UserGetDto> GetByUserNameAynce(string Name)
        {
            throw new NotImplementedException();
        }
    }
}
