using Aplication.Services.Token;
using Domen.AutoGenerated;
using Domen.EmtityDTO.Token;
using Domen.EmtityDTO.UserDto;
using Domen.Model;
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Aplication.Services.UserServices
{
    public  interface IUserService
    {
        Task<User?> RegisterAsync(UserCreateDto createUser);

        Task<string> LoginAsync(LoginDto loginUserModel);
        Task<UserGetDto> CreateUserAynce(UserCreateDto user);
        Task<UserGetDto> UpdateUserAynce(UserUpdateDto user);
        Task<bool> DeleteUserAynce(int Id);
        Task<UserGetDto> GetByIdUserAynce(int Id);
        Task<List<UserGetDto>> GetAllUserAynce();
      
    }
}
