using Aplication;
using Aplication.GenericRepository;
using Domen.AutoGenerated;

namespace Aplication.Repositories
{
    public class OrganizationRepasitory : GenericRepository<Organization>, IOrganizationRepasitory
    {
        public OrganizationRepasitory(ConpanyDbContext conpanyDbContext) : base(conpanyDbContext)
        {
        }
    }
}
