using Aplication.Services.EmployeeServices;
using Aplication.Services.OrganizationServices;
using Aplication.Services.ProjectServices;
using Aplication.Services.ReportServices;
using Aplication.Services.RoleServices;
using Aplication.Services.TaskServices;
using Aplication.Services.Token;
using Aplication.Services.UserServices;
using Aplication.Servises;
using Domen.AutoGenerated;
using Domen.Repositories;
using Infrastructure.GenericRepository;
using Infrastructure.Repositories;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Aplication
{
    public static class ConfigureServices
    {
        public static  void AddConfigureServices(this IServiceCollection services, IConfiguration configuration)
        {
            services.AddScoped<IUserService, UserService>();
            services.AddScoped<ITokenService, TokenService>();
            services.AddScoped<IPasswordHasher<User>, PasswordHasher<User>>();

            services.AddScoped(typeof(IGenericRepository<>), typeof(GenericRepository<>));
            services.AddScoped<IEmployeeRepository, EmployeeRepository>();
            services.AddScoped<IUserRepository, UserRepository>();
            services.AddScoped<IEmployeeService, EmployeeService>();
            services.AddScoped<IUserService, UserService>();
            services.AddScoped<IOrganizationService, OrganizationService>();
            services.AddScoped<IProjectService, ProjectService>();
            services.AddScoped<IRoleService, RoleService>();
            services.AddScoped<IRoleRepository, RoleRepository>();
            services.AddScoped<ITaskService, TaskService>();
            services.AddScoped<ITaskRepository, TaskRepository>();
            services.AddScoped<IOrganizationRepasitory, OrganizationRepasitory>();
            services.AddScoped<IProjectRepository, ProjectRepository>();
            services.AddScoped<IReportService, ReportService>();
        }

    }
}
