using Aplication.GenericRepository;
using Domen.AutoGenerated;
using Domen.EmtityDTO.UserDto;

namespace Aplication.Repositories
{
    public interface IUserRepository : IGenericRepository<User>
    {

        Task<UserGetDto> GetByUserNameAynce(string Name);
        Task<User> GetUserByUsernameAndPasswordAsync(string username, string password);
    }
}
