using Aplication.GenericRepository;
using Domen.AutoGenerated;
using Domen.EmtityDTO.UserDto;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace Aplication.Repositories
{
    public class UserRepository : GenericRepository<User>, IUserRepository
    {
        public UserRepository(ConpanyDbContext conpanyDbContext) : base(conpanyDbContext)
        {
        }
        private readonly ConpanyDbContext _conpanyDbContext;

        public Task<UserGetDto> GetByUserNameAynce(string Name)
        {
            throw new NotImplementedException();
        }

        public async Task<User> GetUserByUsernameAndPasswordAsync(string username, string password)
        {
            var user = await _conpanyDbContext.Users.FirstOrDefaultAsync(u => u.Username == username);
            if (user == null)
            {
                return null;
            }

            var passwordHasher = new PasswordHasher<User>();
            var passwordVerificationResult = passwordHasher.VerifyHashedPassword(user, user.Passwordhash, password);
            if (passwordVerificationResult != PasswordVerificationResult.Success)
            {
                return null;
            }

            return user;
        }

    }
}
