using Aplication.GenericRepository;
using Domen.AutoGenerated;

namespace Aplication.Repositories
{
    public class RoleRepository : GenericRepository<Role>, IRoleRepository
    {
        public RoleRepository(ConpanyDbContext conpanyDbContext) : base(conpanyDbContext)
        {
        }
    }
}
