using Domen.AutoGenerated;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Domen.EmtityDTO.TaskDto
{
    public  class TaskBaseDto
    {


        public int? ProjectId { get; set; }
        public int? EmployeeId { get; set; }
        public int? Taskstatus { get; set; }


     
    }
}
