using Domen.AutoGenerated;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Domen.EmtityDTO.UserDto
{
    public  class UserBaseDto 
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }

        [Column("fullname")]
        [StringLength(255)]
        public string Fullname { get; set; } = null!;

        [Column("username")]
        [StringLength(255)]
        public string Username { get; set; } = null!;

        [Column("email")]
        [StringLength(255)]
        public string Email { get; set; } = null!;

        [Column("passwordhash")]
        public string Passwordhash { get; set; } = null!;

        [Column("createdat", TypeName = "timestamp without time zone")]
        public DateTime Createdat { get; set; }

        [Column("lastlogin", TypeName = "timestamp without time zone")]
        public DateTime? Lastlogin { get; set; }

        [Column("isactive")]
        public bool Isactive { get; set; }

        [Column("phone")]
        [StringLength(255)]
        public string? Phone { get; set; }

        [Column("address")]
        [StringLength(255)]
        public string? Address { get; set; }

        [InverseProperty("User")]
        public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();

        [InverseProperty("Owner")]
        public virtual ICollection<Project> Projects { get; set; } = new List<Project>();

        [InverseProperty("User")]
        public virtual ICollection<Userrole> Userroles { get; set; } = new List<Userrole>();

    }
}
