using Domen.AutoGenerated;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Aplication.Services
{
    public  interface ICompanyService
    {
        Task < Employee> CreateEmployeeAynce (Employee employee);
        Task < Employee> UpdateEmployeeAynce (Employee employee);
        Task < Employee> DeleteEmployeeAynce (int Id);
        Task < Employee> GetByIdEmployee(int Id );
        Task < Employee> GetAllEmployeeAynce ( );

    }
}
