using Domen.AutoGenerated;
using Domen.EmtityDTO.EmployeeDto;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Aplication.Services
{
    public  interface IEmployeeService
    {
        Task<EmployeeGetDto> CreateEmployeeAynce(EmployeeCreateDto employee);
        Task<EmployeeGetDto> UpdateEmployeeAynce(EmployeeUpdateDto employee);
        Task<bool> DeleteEmployeeAynce(int Id);
        Task<EmployeeGetDto> GetByIdEmployee(int Id);
        Task<List<EmployeeGetDto>> GetAllEmployeeAynce();

    }
}
