using Domen.AutoGenerated;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Aplication.Services
{
    public  interface IOrganizationService
    {

        Task<Organization> CreateOrganizationAynce(Organization organization);
        Task<Organization> UpdateOrganizationAynce(Organization organization);
        Task<bool> DeleteOrganizationAynce(int Id);
        Task<Organization> GetByIdOrganizationAynce(int Id);
        Task<List<Organization>> GetAllOrganizationAynce();

    }
}
