using Domen.AutoGenerated;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Aplication.Services
{
    public  interface IProjectService
    {
        Task<Project> CreateProjectAynce(Project project);
        Task<Project> UpdateProjectAynce(Project project);
        Task<bool> DeleteProjectAynce(int Id);
        Task<Project> GetByIdProjectAynce(int Id);
        Task<List<Project>> GetAllProjectAynce();
    }
}
