using Domen.AutoGenerated;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Aplication.Services
{
    public  interface IRoleService
    {
        Task<Role> CreateRoleAynce(Role role);
        Task<Role> UpdateRoleAynce(Role role);
        Task<bool> DeleteRoleAynce(int Id);
        Task<Role> GetByIdRoleAynce(int Id);
        Task<List<Role>> GetAllRoleAynce();

    }
}
