using Domen.AutoGenerated;
using Domen.EmtityDTO.RoleDto;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Aplication.Services
{
    public  interface IRoleService
    {
        Task<RoleGetDto> CreateRoleAsync(RoleCreateDto role);
        Task<RoleGetDto> UpdateRoleAsync(RoleUpdateDto role);
        Task<bool> DeleteRoleAsync(int Id);
        Task<RoleGetDto> GetByIdRoleAsync(int Id);
        Task<List<RoleGetDto>> GetAllRoleAsync();

    }
}
