using Domen.AutoGenerated;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Aplication.Services
{
    public  interface IUserService
    {

        Task<User> CreateUserAynce(User user);
        Task<User> UpdateUserAynce(User user);
        Task<bool> DeleteUserAynce(int Id);
        Task<User> GetByIdUserAynce(int Id);
        Task<List<User>> GetAllUserAynce();
    }
}
