using Domen.AutoGenerated;
using Domen.EmtityDTO.UserDto;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Aplication.Services
{
    public  interface IUserService
    {

        Task<UserGetDto> CreateUserAynce(UserCreateDto user);
        Task<UserGetDto> UpdateUserAynce(UserUpdateDto user);
        Task<bool> DeleteUserAynce(int Id);
        Task<UserGetDto> GetByIdUserAynce(int Id);
        Task<List<UserGetDto>> GetAllUserAynce();
    }
}
