using Aplication.GenericRepository;
using Domen.AutoGenerated;

namespace Aplication.Repositories;

public class EmployeeRepository : GenericRepository<Employee>, IEmployeeRepository
{
    public EmployeeRepository(ConpanyDbContext conpanyDbContext) : base(conpanyDbContext)
    {
    }
}
