using Domen.AutoGenerated;
using Domen.EmtityDTO.OrganizationDto;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Aplication.Services.OrganizationServices
{
    public interface IOrganizationService
    {

        Task<OrganizationGetDto> CreateOrganizationAsync(OrganizationCreateDto organization);
        Task<OrganizationGetDto> UpdateOrganizationAsync(OrganizationUpdateDto organization);
        Task<bool> DeleteOrganizationAsync(int Id);
        Task<OrganizationGetDto> GetByIdOrganizationAsync(int Id);
        Task<List<OrganizationGetDto>> GetAllOrganizationAsync();

    }
}
