using Aplication.Services;
using Domen.AutoGenerated;
using Domen.EmtityDTO.Token;
using Domen.EmtityDTO.UserDto;
using Domen.Model;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Infrastructure.Servises.TokenService
{
    public class IdentityService : IIdentityServise
    {
         private readonly IIdentityServise _identityServise;
        private readonly IUserService _userService;
        private readonly ConpanyDbContext _conpanyDbContext;

        public IdentityService(IIdentityServise identityServise, IUserService userService, ConpanyDbContext conpanyDbContext)
        {
            _identityServise = identityServise;
            _userService = userService;
            _conpanyDbContext = conpanyDbContext;
        }

        public Task<bool> IsValidRefreshToken(string refreshToken, int userId)
        {
            throw new NotImplementedException();
        }

        public Task<UserGetDto> LoginAsync(UserCreateDto userCreate)
        {
            throw new NotImplementedException();
        }

        public Task<bool> LogoutAsync()
        {
            throw new NotImplementedException();
        }

        public Task<TokenDto> RefreshTokenAsync(Token token, int Id)
        {
            throw new NotImplementedException();
        }

        public async  Task<TokenDto> RegisterAsync(User user)
        {
            throw new NotImplementedException();
            

        }

        public Task<bool> SaveRefreshToken(string refreshToken, User user)
        {
            throw new NotImplementedException();
        }
    }
}
