using Aplication.Services;
using Domen.AutoGenerated;
using Domen.EmtityDTO.Token;
using Domen.EmtityDTO.UserDto;
using Domen.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Infrastructure.Servises.TokenService
{
    public class IdentityService : IIdentityServise
    {

        public Task<bool> IsValidRefreshToken(string refreshToken, int userId)
        {
            throw new NotImplementedException();
        }

        public Task<UserGetDto> LoginAsync(UserCreateDto userCreate)
        {
            throw new NotImplementedException();
        }

        public Task<bool> LogoutAsync()
        {
            throw new NotImplementedException();
        }

        public Task<TokenDto> RefreshTokenAsync(Token token, int Id)
        {
            throw new NotImplementedException();
        }

        public Task<UserGetDto> RegisterAsync(User user)
        {
            throw new NotImplementedException();
        }

        public Task<bool> SaveRefreshToken(string refreshToken, User user)
        {
            throw new NotImplementedException();
        }
    }
}
