using Aplication.Services;
using Domen.AutoGenerated;
using Domen.EmtityDTO.ProjectDto;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Infrastructure.Servises
{
    public class ProjectService : IProjectService
    {
        public Task<ProjectGetDto> CreateProjectAsync(ProjectCreateDto project)
        {
            throw new NotImplementedException();
        }

        public Task<bool> DeleteProjectAsync(int Id)
        {
            throw new NotImplementedException();
        }

        public Task<List<Project>> GetAllProjectAsync()
        {
            throw new NotImplementedException();
        }

        public Task<Project> GetByIdProjectAsync(int Id)
        {
            throw new NotImplementedException();
        }

        public Task<ProjectGetDto> UpdateProjectAsync(ProjectUpdateDto project)
        {
            throw new NotImplementedException();
        }
    }
}
