using Domen.AutoGenerated;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace Domen.EmtityDTO.EmployeeDto
{
    public class EmployeeBeseDto
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string EmployeeName { get; set; } = null!;
        public int? EmployeeLevel { get; set; }
        public int? OrganizationId { get; set; }
        public string Email { get; set; } = null!;
        public string Phonenumber { get; set; } = null!;
        public DateOnly Hiredate { get; set; }
        public int? Departmentid { get; set; }
        public decimal Salary { get; set; }
        public bool Isactive { get; set; }
        public virtual ICollection<AssigneeEt> AssigneeEts { get; set; } = new List<AssigneeEt>();
        public virtual ICollection<Assignee> Assignees { get; set; } = new List<Assignee>();

        public virtual EmployeeLevel? EmployeeLevelNavigation { get; set; }
        public virtual Organization? Organization { get; set; }

        public virtual ICollection<Project> Projects { get; set; } = new List<Project>();
        public virtual ICollection<System.Threading.Tasks.Task> Tasks { get; set; } = new List<System.Threading.Tasks.Task>();
        public virtual User User { get; set; } = null!;
    }
}
